More initscript mucking

diff --git a/contrib/initscripts/qfs-chunkserver b/contrib/initscripts/qfs-chunkserver
--- a/contrib/initscripts/qfs-chunkserver
+++ b/contrib/initscripts/qfs-chunkserver
@@ -34,34 +34,89 @@ stderr_log="${logdir}/chunkserver.err"
 
 lockfile=/var/lock/subsys/qfs-chunkserver
 
+# Set up a default search path.
+PATH="/sbin:/usr/sbin:/bin:/usr/bin"
+export PATH
+
+# Get a sane screen width
+[ -z "${COLUMNS:-}" ] && COLUMNS=80
+
+[ -z "${CONSOLETYPE:-}" ] && CONSOLETYPE="$(/sbin/consoletype)"
+
+# Read in our configuration
+if [ -z "${BOOTUP:-}" ]; then
+  if [ -f /etc/sysconfig/init ]; then
+      . /etc/sysconfig/init
+  else
+    BOOTUP=color
+    RES_COL=60
+    MOVE_TO_COL="echo -en \\033[${RES_COL}G"
+    SETCOLOR_SUCCESS="echo -en \\033[1;32m"
+    SETCOLOR_FAILURE="echo -en \\033[1;31m"
+    SETCOLOR_WARNING="echo -en \\033[1;33m"
+    SETCOLOR_NORMAL="echo -en \\033[0;39m"
+    LOGLEVEL=1
+  fi
+  if [ "$CONSOLETYPE" = "serial" ]; then
+      BOOTUP=serial
+      MOVE_TO_COL=
+      SETCOLOR_SUCCESS=
+      SETCOLOR_FAILURE=
+      SETCOLOR_WARNING=
+      SETCOLOR_NORMAL=
+  fi
+fi
+
+echo_success() {
+  [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+  echo -n "["
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
+  echo -n $"  OK  "
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+  echo -n "]"
+  echo -ne "\r"
+  return 0
+}
+
+echo_failure() {
+  [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+  echo -n "["
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+  echo -n $"FAILED"
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+  echo -n "]"
+  echo -ne "\r"
+  return 1
+}
+
 start() {
-    [ -x ${exec} ] || exit 5
-    [ -f ${config} ] || exit 6
-    echo -n $"Starting $prog: "
-    # Starts chunkserver via daemonize for fork excellence.
-    start_daemon daemonize -o ${stdout_log} -e ${stderr_log} -p ${pid_file} ${exec} ${config}
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && touch $lockfile
-    return $retval
+  [ -x ${exec} ] || exit 5
+  [ -f ${config} ] || exit 6
+  echo -n $"Starting $prog: "
+  # Starts chunkserver via daemonize for fork excellence.
+  start_daemon daemonize -o ${stdout_log} -e ${stderr_log} -p ${pid_file} ${exec} ${config}
+  retval=$?
+  [ $retval -eq 0 ] && (echo_success; touch $lockfile) || echo_failure
+  echo
+  return $retval
 }
 
 stop() {
-    echo -n $"Stopping $prog: "
-    killproc -p ${pid_file} ${exec}
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && rm -f $lockfile
-    return $retval
+  echo -n $"Stopping $prog: "
+  killproc -p ${pid_file} ${exec}
+  retval=$?
+  [ $retval -eq 0 ] && (echo_success; rm -f $lockfile) || echo_failure
+  echo
+  return $retval
 }
 
 restart() {
-    stop
-    start
+  stop
+  start
 }
 
 reload() {
-    restart
+  restart
 }
 
 force_reload() {
@@ -69,50 +124,47 @@ force_reload() {
 }
 
 rh_status() {
-    pid=`pidofproc -p ${pid_file} ${prog}`
-    if [ $? -eq 0 ]; then
-        echo "${prog} (pid ${pid}) is running..."
-        return 0
-    else
-        echo "${prog} is stopped"
-        return 1
-    fi
+  pid=`pidofproc -p ${pid_file} ${prog}`
+  if [ $? -eq 0 ]; then
+    echo "${prog} (pid ${pid}) is running..."
+    return 0
+  else
+    echo "${prog} is stopped"
+    return 1
+  fi
 }
 
 rh_status_q() {
-    rh_status >/dev/null 2>&1
+  rh_status >/dev/null 2>&1
 }
 
 
 case "$1" in
-    start)
-        rh_status_q && exit 0
-        $1
-        ;;
-    stop)
-        rh_status_q || exit 0
-        $1
-        ;;
-    restart)
-        $1
-        ;;
-    reload)
-        rh_status_q || exit 7
-        $1
-        ;;
-    force-reload)
-        force_reload
-        ;;
-    status)
-        rh_status
-        ;;
-    condrestart|try-restart)
-        rh_status_q || exit 0
-        restart
-        ;;
-    *)
-        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
-        exit 2
+  start)
+    $1
+    ;;
+  stop)
+    $1
+    ;;
+  restart)
+    $1
+    ;;
+  reload)
+    $1
+    ;;
+  force-reload)
+    force_reload
+    ;;
+  status)
+    rh_status
+    ;;
+  condrestart|try-restart)
+    rh_status_q || exit 0
+    restart
+    ;;
+  *)
+    echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
+    exit 2
 esac
 exit $?
 
